# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "@types/color-name-1.1.1" = {
      name = "_at_types_slash_color-name";
      packageName = "@types/color-name";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/color-name/-/color-name-1.1.1.tgz";
        sha512 = "rr+OQyAjxze7GgWrSaJwydHStIhHq2lvY3BOC2Mj7KnzI7XK0Uw1TOOdI9lDoajEbSWLiYgoo4f1R51erQfhPQ==";
      };
    };
    "abort-controller-3.0.0" = {
      name = "abort-controller";
      packageName = "abort-controller";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/abort-controller/-/abort-controller-3.0.0.tgz";
        sha512 = "h8lQ8tacZYnR3vNQTgibj+tODHI5/+l06Au2Pcriv/Gmet0eaj4TwWH41sO9wnHDiQsEj19q0drzdWdeAHtweg==";
      };
    };
    "agent-base-6.0.0" = {
      name = "agent-base";
      packageName = "agent-base";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/agent-base/-/agent-base-6.0.0.tgz";
        sha512 = "j1Q7cSCqN+AwrmDd+pzgqc0/NpC655x2bUf5ZjRIO77DcNBFmh+OgRNzF6OKdCC9RSCb19fGd99+bhXFdkRNqw==";
      };
    };
    "ansi-regex-2.1.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
        sha1 = "c3b33ab5ee360d86e0e628f0468ae7ef27d654df";
      };
    };
    "ansi-styles-2.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz";
        sha1 = "b432dd3358b634cf75e1e4664368240533c1ddbe";
      };
    };
    "ansi-styles-4.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-4.2.1.tgz";
        sha512 = "9VGjrMsG1vePxcSweQsN20KY/c4zN0h9fLjqAbwbPfahM3t+NL+M9HC8xeXG2I8pX5NoamTGNuomEUFI7fcUjA==";
      };
    };
    "array-flatten-2.1.2" = {
      name = "array-flatten";
      packageName = "array-flatten";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-flatten/-/array-flatten-2.1.2.tgz";
        sha512 = "hNfzcOV8W4NdualtqBFPyVO+54DSJuZGY9qT4pRroB6S9e3iiido2ISIC5h9R2sPJ8H3FHCIiEnsv1lPXO3KtQ==";
      };
    };
    "arrify-2.0.1" = {
      name = "arrify";
      packageName = "arrify";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/arrify/-/arrify-2.0.1.tgz";
        sha512 = "3duEwti880xqi4eAMN8AyR4a0ByT90zoYdLlevfrvU43vb0YZwZVfxOgxWrLXXXpyugL0hNZc9G6BiB5B3nUug==";
      };
    };
    "async-limiter-1.0.1" = {
      name = "async-limiter";
      packageName = "async-limiter";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/async-limiter/-/async-limiter-1.0.1.tgz";
        sha512 = "csOlWGAcRFJaI6m+F2WKdnMKr4HhdhFVBk0H/QbJFMCr+uO2kwohwXQPxw/9OCxp05r5ghVBFSyioixx3gfkNQ==";
      };
    };
    "balanced-match-1.0.0" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz";
        sha1 = "89b4d199ab2bee49de164ea02b89ce462d71b767";
      };
    };
    "base64-js-1.3.1" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.3.1.tgz";
        sha512 = "mLQ4i2QO1ytvGWFWmcngKO//JXAQueZvwEKtjgQFM4jIK0kU+ytMfplL8j+n5mspOfjHwoAg+9yhb7BwAHm36g==";
      };
    };
    "bignumber.js-7.2.1" = {
      name = "bignumber.js";
      packageName = "bignumber.js";
      version = "7.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bignumber.js/-/bignumber.js-7.2.1.tgz";
        sha512 = "S4XzBk5sMB+Rcb/LNcpzXr57VRTxgAvaAEDAl1AwRx27j00hT84O6OkteE7u8UB3NuaaygCRrEpqox4uDOrbdQ==";
      };
    };
    "binary-0.3.0" = {
      name = "binary";
      packageName = "binary";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/binary/-/binary-0.3.0.tgz";
        sha1 = "9f60553bc5ce8c3386f3b553cff47462adecaa79";
      };
    };
    "binrpc-3.3.1" = {
      name = "binrpc";
      packageName = "binrpc";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/binrpc/-/binrpc-3.3.1.tgz";
        sha512 = "NGntqdrZTUk8Jt26lKlPckP28XhU5SwVhskZma0xHVfa7V8WJwz4AGjKRTKa6tXS1Nf1fdYp1WgPmdUEVjtfQw==";
      };
    };
    "bl-1.2.2" = {
      name = "bl";
      packageName = "bl";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bl/-/bl-1.2.2.tgz";
        sha512 = "e8tQYnZodmebYDWGH7KMRvtzKXaJHx3BbilrgZCfvyLUYdKpK1t5PSPmpkny/SgiTSCnjfLW7v5rlONXVFkQEA==";
      };
    };
    "bonjour-hap-3.5.4" = {
      name = "bonjour-hap";
      packageName = "bonjour-hap";
      version = "3.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/bonjour-hap/-/bonjour-hap-3.5.4.tgz";
        sha512 = "MgU27SEZYQ09Skm71Xa7SZoAg259V4IlAJNWaloFVMlYDn1OjJy3nkwSixRHnDzrcLWocVI84f9exI1ObZChBw==";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "buffer-equal-constant-time-1.0.1" = {
      name = "buffer-equal-constant-time";
      packageName = "buffer-equal-constant-time";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-equal-constant-time/-/buffer-equal-constant-time-1.0.1.tgz";
        sha1 = "f8e71132f7ffe6e01a5c9697a4c6f3e48d5cc819";
      };
    };
    "buffer-from-1.1.1" = {
      name = "buffer-from";
      packageName = "buffer-from";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-from/-/buffer-from-1.1.1.tgz";
        sha512 = "MQcXEUbCKtEo7bhqEs6560Hyd4XaovZlO/k9V3hjVUF/zwW7KBVdSK4gIt/bzwS9MbR5qob+F5jusZsb0YQK2A==";
      };
    };
    "buffer-indexof-1.1.1" = {
      name = "buffer-indexof";
      packageName = "buffer-indexof";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-indexof/-/buffer-indexof-1.1.1.tgz";
        sha512 = "4/rOEg86jivtPTeOUUT61jJO1Ya1TrR/OkqCSZDyq84WJh3LuuiphBYJN+fm5xufIk4XAFcEwte/8WzC8If/1g==";
      };
    };
    "buffer-shims-1.0.0" = {
      name = "buffer-shims";
      packageName = "buffer-shims";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-shims/-/buffer-shims-1.0.0.tgz";
        sha1 = "9978ce317388c649ad8793028c3477ef044a8b51";
      };
    };
    "buffers-0.1.1" = {
      name = "buffers";
      packageName = "buffers";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffers/-/buffers-0.1.1.tgz";
        sha1 = "b24579c3bed4d6d396aeee6d9a8ae7f5482ab7bb";
      };
    };
    "callback-stream-1.1.0" = {
      name = "callback-stream";
      packageName = "callback-stream";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/callback-stream/-/callback-stream-1.1.0.tgz";
        sha1 = "4701a51266f06e06eaa71fc17233822d875f4908";
      };
    };
    "chainsaw-0.1.0" = {
      name = "chainsaw";
      packageName = "chainsaw";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chainsaw/-/chainsaw-0.1.0.tgz";
        sha1 = "5eab50b28afe58074d0d58291388828b5e5fbc98";
      };
    };
    "chalk-1.1.3" = {
      name = "chalk";
      packageName = "chalk";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz";
        sha1 = "a8115c55e4a702fe4d150abd3872822a7e09fc98";
      };
    };
    "chalk-4.0.0" = {
      name = "chalk";
      packageName = "chalk";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-4.0.0.tgz";
        sha512 = "N9oWFcegS0sFr9oh1oz2d7Npos6vNoWW9HvtCg5N1KRFpUhaAhvTv5Y58g880fZaEYSNm3qDz8SU1UrGvp+n7A==";
      };
    };
    "color-convert-2.0.1" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-2.0.1.tgz";
        sha512 = "RRECPsj7iu/xb5oKYcsFHSppFNnsj/52OVTRKb4zP5onXwVF3zVmmToNcOfGC+CRDpfK/U584fMg38ZHCaElKQ==";
      };
    };
    "color-name-1.1.4" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.4.tgz";
        sha512 = "dOy+3AuW3a2wNbZHIuMZpTcgjGuLU/uBL/ubcZF9OXbDo8ff4O8yVp5Bf0efS8uEoYo5q4Fx7dY9OgQGXgAsQA==";
      };
    };
    "commander-2.8.1" = {
      name = "commander";
      packageName = "commander";
      version = "2.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.8.1.tgz";
        sha1 = "06be367febfda0c330aa1e2a072d3dc9762425d4";
      };
    };
    "commist-1.1.0" = {
      name = "commist";
      packageName = "commist";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commist/-/commist-1.1.0.tgz";
        sha512 = "rraC8NXWOEjhADbZe9QBNzLAN5Q3fsTPQtBV+fEVj6xKIgDgNiEVE6ZNfHpZOqfQ21YUzfVNUXLOEZquYvQPPg==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "concat-stream-1.6.2" = {
      name = "concat-stream";
      packageName = "concat-stream";
      version = "1.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-stream/-/concat-stream-1.6.2.tgz";
        sha512 = "27HBghJxjiZtIk3Ycvn/4kbJk/1uZuJFfuPEns6LaEvpvG1f0hTea8lilrouyo9mVc2GWdcEZ8OLoGmSADlrCw==";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "d-1.0.1" = {
      name = "d";
      packageName = "d";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d/-/d-1.0.1.tgz";
        sha512 = "m62ShEObQ39CfralilEQRjH6oAMtNCV1xJyEx5LpRYUVN+EviphDgUc/F3hnYbADmkiNs67Y+3ylmlG7Lnu+FA==";
      };
    };
    "debug-2.6.9" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz";
        sha512 = "bC7ElrdJaJnPbAP+1EotYvqZsb3ecl5wi6Bfi6BJTUcNowp6cvspg0jXznRTKDjm/E7AdgFBVeAPVMNcKGsHMA==";
      };
    };
    "debug-4.1.1" = {
      name = "debug";
      packageName = "debug";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.1.1.tgz";
        sha512 = "pYAIzeRo8J6KPEaJ0VWOh5Pzkbw/RetuzehGM7QRRX5he4fPHx2rdKMB256ehJCkX+XRQm16eZLqLNS8RSZXZw==";
      };
    };
    "decimal.js-7.5.1" = {
      name = "decimal.js";
      packageName = "decimal.js";
      version = "7.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/decimal.js/-/decimal.js-7.5.1.tgz";
        sha512 = "1K5Y6MykxQYfHBcFfAj2uBaLmwreq4MsjsvrlgcEOvg+X82IeeXlIVIVkBMiypksu+yo9vcYP6lfU3qTedofSQ==";
      };
    };
    "deep-equal-1.1.1" = {
      name = "deep-equal";
      packageName = "deep-equal";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-equal/-/deep-equal-1.1.1.tgz";
        sha512 = "yd9c5AdiqVcR+JjcwUQb9DkhJc8ngNr0MahEBGvDiJw8puWab2yZlh+nkasOnZP+EGTAP6rRp2JzJhJZzvNF8g==";
      };
    };
    "define-properties-1.1.3" = {
      name = "define-properties";
      packageName = "define-properties";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-properties/-/define-properties-1.1.3.tgz";
        sha512 = "3MqfYKj2lLzdMSf8ZIZE/V+Zuy+BgD6f164e8K2w7dgnpKArBDerGYpM46IYYcjnkdPNMjPk9A6VFB8+3SKlXQ==";
      };
    };
    "dns-equal-1.0.0" = {
      name = "dns-equal";
      packageName = "dns-equal";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dns-equal/-/dns-equal-1.0.0.tgz";
        sha1 = "b39e7f1da6eb0a75ba9c17324b34753c47e0654d";
      };
    };
    "dns-packet-4.2.0" = {
      name = "dns-packet";
      packageName = "dns-packet";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dns-packet/-/dns-packet-4.2.0.tgz";
        sha512 = "bn1AKpfkFbm0MIioOMHZ5qJzl2uypdBwI4nYNsqvhjsegBhcKJUlCrMPWLx6JEezRjxZmxhtIz/FkBEur2l8Cw==";
      };
    };
    "dns-txt-2.0.2" = {
      name = "dns-txt";
      packageName = "dns-txt";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/dns-txt/-/dns-txt-2.0.2.tgz";
        sha1 = "b91d806f5d27188e4ab3e7d107d881a1cc4642b6";
      };
    };
    "duplexify-3.7.1" = {
      name = "duplexify";
      packageName = "duplexify";
      version = "3.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/duplexify/-/duplexify-3.7.1.tgz";
        sha512 = "07z8uv2wMyS51kKhD1KsdXJg5WQ6t93RneqRxUHnskXVtlYYkLqM0gqStQZ3pj073g687jPCHrqNfCzawLYh5g==";
      };
    };
    "ecdsa-sig-formatter-1.0.11" = {
      name = "ecdsa-sig-formatter";
      packageName = "ecdsa-sig-formatter";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecdsa-sig-formatter/-/ecdsa-sig-formatter-1.0.11.tgz";
        sha512 = "nagl3RYrbNv6kQkeJIpt6NJZy8twLB/2vtz6yN9Z4vRKHN4/QZJIEbqohALSgwKdnksuY3k5Addp5lg8sVoVcQ==";
      };
    };
    "end-of-stream-1.4.4" = {
      name = "end-of-stream";
      packageName = "end-of-stream";
      version = "1.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/end-of-stream/-/end-of-stream-1.4.4.tgz";
        sha512 = "+uw1inIHVPQoaVuHzRyXd21icM+cnt4CzD5rW+NC1wjOUSTOs+Te7FOv7AhN7vS9x/oIyhLP5PR1H+phQAHu5Q==";
      };
    };
    "es-abstract-1.17.5" = {
      name = "es-abstract";
      packageName = "es-abstract";
      version = "1.17.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-abstract/-/es-abstract-1.17.5.tgz";
        sha512 = "BR9auzDbySxOcfog0tLECW8l28eRGpDpU3Dm3Hp4q/N+VtLTmyj4EUN088XZWQDW/hzj6sYRDXeOFsaAODKvpg==";
      };
    };
    "es-to-primitive-1.2.1" = {
      name = "es-to-primitive";
      packageName = "es-to-primitive";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-to-primitive/-/es-to-primitive-1.2.1.tgz";
        sha512 = "QCOllgZJtaUo9miYBcLChTUaHNjJF3PYs1VidD7AwiEj1kYxKeQTctLAezAOH5ZKRH0g2IgPn6KwB4IT8iRpvA==";
      };
    };
    "es5-ext-0.10.53" = {
      name = "es5-ext";
      packageName = "es5-ext";
      version = "0.10.53";
      src = fetchurl {
        url = "https://registry.npmjs.org/es5-ext/-/es5-ext-0.10.53.tgz";
        sha512 = "Xs2Stw6NiNHWypzRTY1MtaG/uJlwCk8kH81920ma8mvN8Xq1gsfhZvpkImLQArw8AHnv8MT2I45J3c0R8slE+Q==";
      };
    };
    "es6-iterator-2.0.3" = {
      name = "es6-iterator";
      packageName = "es6-iterator";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-iterator/-/es6-iterator-2.0.3.tgz";
        sha1 = "a7de889141a05a94b0854403b2d0a0fbfa98f3b7";
      };
    };
    "es6-map-0.1.5" = {
      name = "es6-map";
      packageName = "es6-map";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-map/-/es6-map-0.1.5.tgz";
        sha1 = "9136e0503dcc06a301690f0bb14ff4e364e949f0";
      };
    };
    "es6-set-0.1.5" = {
      name = "es6-set";
      packageName = "es6-set";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-set/-/es6-set-0.1.5.tgz";
        sha1 = "d2b3ec5d4d800ced818db538d28974db0a73ccb1";
      };
    };
    "es6-symbol-3.1.1" = {
      name = "es6-symbol";
      packageName = "es6-symbol";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-symbol/-/es6-symbol-3.1.1.tgz";
        sha1 = "bf00ef4fdab6ba1b46ecb7b629b4c7ed5715cc77";
      };
    };
    "es6-symbol-3.1.3" = {
      name = "es6-symbol";
      packageName = "es6-symbol";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-symbol/-/es6-symbol-3.1.3.tgz";
        sha512 = "NJ6Yn3FuDinBaBRWl/q5X/s4koRHBrgKAu+yGI6JCBeiu3qrcbJhwT2GeR/EXVfylRk8dpQVJoLEFhK+Mu31NA==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "event-emitter-0.3.5" = {
      name = "event-emitter";
      packageName = "event-emitter";
      version = "0.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/event-emitter/-/event-emitter-0.3.5.tgz";
        sha1 = "df8c69eef1647923c7157b9ce83840610b02cc39";
      };
    };
    "event-target-shim-5.0.1" = {
      name = "event-target-shim";
      packageName = "event-target-shim";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/event-target-shim/-/event-target-shim-5.0.1.tgz";
        sha512 = "i/2XbnSz/uxRCU6+NdVJgKWDTM427+MqYbkQzD321DuCQJUqOuJKIA0IM2+W2xtYHdKOmZ4dR6fExsd4SXL+WQ==";
      };
    };
    "ext-1.4.0" = {
      name = "ext";
      packageName = "ext";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ext/-/ext-1.4.0.tgz";
        sha512 = "Key5NIsUxdqKg3vIsdw9dSuXpPCQ297y6wBjL30edxwPgt2E44WcWBZey/ZvUc6sERLTxKdyCu4gZFmUbk1Q7A==";
      };
    };
    "extend-3.0.2" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.2.tgz";
        sha512 = "fjquC59cD7CyW6urNXK0FBufkZcoiGG80wTuPujX590cB5Ttln20E2UB4S/WARVqhXffZl2LNgS+gQdPIIim/g==";
      };
    };
    "fakegato-history-0.5.6" = {
      name = "fakegato-history";
      packageName = "fakegato-history";
      version = "0.5.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/fakegato-history/-/fakegato-history-0.5.6.tgz";
        sha512 = "LlsOkiw9LntVlRlBkssD5ozhEkQzYuEJUlvXk5YAgBQcWzk19PQ5g+NoKfs6SRY1qAeC1onb65hes4mCvY+JmA==";
      };
    };
    "fast-srp-hap-1.2.0" = {
      name = "fast-srp-hap";
      packageName = "fast-srp-hap";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-srp-hap/-/fast-srp-hap-1.2.0.tgz";
        sha512 = "WgC3eJEaQo94pq6Ua+l4zdceMLkDXvhZ4OpyQsFdlTFDH7GwJ6fikr+C/mkKzaIxbnODkqee8cOd0KjuW2ebKQ==";
      };
    };
    "fast-text-encoding-1.0.1" = {
      name = "fast-text-encoding";
      packageName = "fast-text-encoding";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-text-encoding/-/fast-text-encoding-1.0.1.tgz";
        sha512 = "x4FEgaz3zNRtJfLFqJmHWxkMDDvXVtaznj2V9jiP8ACUJrUgist4bP9FmDL2Vew2Y9mEQI/tG4GqabaitYp9CQ==";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "gaxios-2.3.4" = {
      name = "gaxios";
      packageName = "gaxios";
      version = "2.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/gaxios/-/gaxios-2.3.4.tgz";
        sha512 = "US8UMj8C5pRnao3Zykc4AAVr+cffoNKRTg9Rsf2GiuZCW69vgJj38VK2PzlPuQU73FZ/nTk9/Av6/JGcE1N9vA==";
      };
    };
    "gaxios-3.0.2" = {
      name = "gaxios";
      packageName = "gaxios";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/gaxios/-/gaxios-3.0.2.tgz";
        sha512 = "cLOetrsKOBLPwjzVyFzirYaGjrhtYjbKUHp6fQpsio2HH8Mil35JTFQLgkV5D3CCXV7Gnd5V69/m4C9rMBi9bA==";
      };
    };
    "gcp-metadata-3.5.0" = {
      name = "gcp-metadata";
      packageName = "gcp-metadata";
      version = "3.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/gcp-metadata/-/gcp-metadata-3.5.0.tgz";
        sha512 = "ZQf+DLZ5aKcRpLzYUyBS3yo3N0JSa82lNDO8rj3nMSlovLcz2riKFBsYgDzeXcv75oo5eqB2lx+B14UvPoCRnA==";
      };
    };
    "gcp-metadata-4.0.1" = {
      name = "gcp-metadata";
      packageName = "gcp-metadata";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/gcp-metadata/-/gcp-metadata-4.0.1.tgz";
        sha512 = "hX2Ge7RJqESJ3gTfitpJWbdXqxxzgUFX5KVPhE02l9jq17rKKsTeB5h7v7Cky7yhLPfMYcirojC6VWU26lVyCQ==";
      };
    };
    "glob-7.1.6" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.6.tgz";
        sha512 = "LwaxwyZ72Lk7vZINtNNrywX0ZuLyStrdDtabefZKAY5ZGJhVtgdznluResxNmPitE0SAO+O26sWTHeKSI2wMBA==";
      };
    };
    "glob-parent-3.1.0" = {
      name = "glob-parent";
      packageName = "glob-parent";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-parent/-/glob-parent-3.1.0.tgz";
        sha1 = "9e6af6299d8d3bd2bd40430832bd113df906c5ae";
      };
    };
    "glob-stream-6.1.0" = {
      name = "glob-stream";
      packageName = "glob-stream";
      version = "6.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-stream/-/glob-stream-6.1.0.tgz";
        sha1 = "7045c99413b3eb94888d83ab46d0b404cc7bdde4";
      };
    };
    "google-auth-library-5.9.2" = {
      name = "google-auth-library";
      packageName = "google-auth-library";
      version = "5.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/google-auth-library/-/google-auth-library-5.9.2.tgz";
        sha512 = "rBE1YTOZ3/Hu6Mojkr+UUmbdc/F28hyMGYEGxjyfVA9ZFmq12oqS3AeftX4h9XpdVIcxPooSo8hECYGT6B9XqQ==";
      };
    };
    "google-auth-library-6.0.0" = {
      name = "google-auth-library";
      packageName = "google-auth-library";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/google-auth-library/-/google-auth-library-6.0.0.tgz";
        sha512 = "uLydy1t6SHN/EvYUJrtN3GCHFrnJ0c8HJjOxXiGjoTuYHIoCUT3jVxnzmjHwVnSdkfE9Akasm2rM6qG1COTXfQ==";
      };
    };
    "google-p12-pem-2.0.4" = {
      name = "google-p12-pem";
      packageName = "google-p12-pem";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/google-p12-pem/-/google-p12-pem-2.0.4.tgz";
        sha512 = "S4blHBQWZRnEW44OcR7TL9WR+QCqByRvhNDZ/uuQfpxywfupikf/miba8js1jZi6ZOGv5slgSuoshCWh6EMDzg==";
      };
    };
    "google-p12-pem-3.0.1" = {
      name = "google-p12-pem";
      packageName = "google-p12-pem";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/google-p12-pem/-/google-p12-pem-3.0.1.tgz";
        sha512 = "VlQgtozgNVVVcYTXS36eQz4PXPt9gIPqLOhHN0QiV6W6h4qSCNVKPtKC5INtJsaHHF2r7+nOIa26MJeJMTaZEQ==";
      };
    };
    "googleapis-47.0.0" = {
      name = "googleapis";
      packageName = "googleapis";
      version = "47.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/googleapis/-/googleapis-47.0.0.tgz";
        sha512 = "+Fnjgcc3Na/rk57dwxqW1V0HJXJFjnt3aqFlckULqAqsPkmex/AyJJe6MSlXHC37ZmlXEb9ZtPGUp5ZzRDXpHg==";
      };
    };
    "googleapis-49.0.0" = {
      name = "googleapis";
      packageName = "googleapis";
      version = "49.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/googleapis/-/googleapis-49.0.0.tgz";
        sha512 = "UoUuDbOzLxtU6fZnDyj6IvYvczBYP08RK3Sn0AknssQJceUYiHldaCjEFT1PDcT9MiKSJrbPze6PRdzQDny0Xw==";
      };
    };
    "googleapis-common-3.2.2" = {
      name = "googleapis-common";
      packageName = "googleapis-common";
      version = "3.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/googleapis-common/-/googleapis-common-3.2.2.tgz";
        sha512 = "sTEXlauVce4eMX0S6hVoiWgxVzQZ7dc16KcGF7eh+A+uIyDgXqnuwOMZw+svX4gOJv6w4ACecm23Qh9UDaldsw==";
      };
    };
    "googleapis-common-4.1.0" = {
      name = "googleapis-common";
      packageName = "googleapis-common";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/googleapis-common/-/googleapis-common-4.1.0.tgz";
        sha512 = "/T+GflstRAbXbf33zeutDXhXj25I1gKwaWNJ4kWSJVSVpXIZugOX8K7iq3uFCQCOJzehPuPLAC2u8iEf6jN0dw==";
      };
    };
    "graceful-readlink-1.0.1" = {
      name = "graceful-readlink";
      packageName = "graceful-readlink";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-readlink/-/graceful-readlink-1.0.1.tgz";
        sha1 = "4cafad76bc62f02fa039b2f94e9a3dd3a391a725";
      };
    };
    "gtoken-4.1.4" = {
      name = "gtoken";
      packageName = "gtoken";
      version = "4.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/gtoken/-/gtoken-4.1.4.tgz";
        sha512 = "VxirzD0SWoFUo5p8RDP8Jt2AGyOmyYcT/pOUgDKJCK+iSw0TMqwrVfY37RXTNmoKwrzmDHSk0GMT9FsgVmnVSA==";
      };
    };
    "gtoken-5.0.1" = {
      name = "gtoken";
      packageName = "gtoken";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/gtoken/-/gtoken-5.0.1.tgz";
        sha512 = "33w4FNDkUcyIOq/TqyC+drnKdI4PdXmWp9lZzssyEQKuvu9ZFN3KttaSnDKo52U3E51oujVGop93mKxmqO8HHg==";
      };
    };
    "hap-nodejs-0.4.51" = {
      name = "hap-nodejs";
      packageName = "hap-nodejs";
      version = "0.4.51";
      src = fetchurl {
        url = "https://registry.npmjs.org/hap-nodejs/-/hap-nodejs-0.4.51.tgz";
        sha512 = "d+b0KsakGRC5IgYBBCuqkAFzj8iKAHVw0bKreT8vmhK4b43FTVWiSwi5MWXApoYQUkbPux+xnVYqwMo+Zviieg==";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 = "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "has-ansi-2.0.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz";
        sha1 = "34f5049ce1ecdf2b0649af3ef24e45ed35416d91";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "has-symbols-1.0.1" = {
      name = "has-symbols";
      packageName = "has-symbols";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-symbols/-/has-symbols-1.0.1.tgz";
        sha512 = "PLcsoqu++dmEIZB+6totNFKq/7Do+Z0u4oT0zKOJNl3lYK6vGwwu2hjHs+68OEZbTjiUE9bgOABXbP/GvrS0Kg==";
      };
    };
    "help-me-1.1.0" = {
      name = "help-me";
      packageName = "help-me";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/help-me/-/help-me-1.1.0.tgz";
        sha1 = "8f2d508d0600b4a456da2f086556e7e5c056a3c6";
      };
    };
    "homebridge-lib-4.5.7" = {
      name = "homebridge-lib";
      packageName = "homebridge-lib";
      version = "4.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/homebridge-lib/-/homebridge-lib-4.5.7.tgz";
        sha512 = "Q3wz78nTq67ipC4NtuTZ5VgnfrUw9c5TkuieTmrbtUzjLUo/q0uk+nVkpBePp+HpWC9TfxzCEP8gh76Tn2W1Bw==";
      };
    };
    "homematic-xmlrpc-1.0.2" = {
      name = "homematic-xmlrpc";
      packageName = "homematic-xmlrpc";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/homematic-xmlrpc/-/homematic-xmlrpc-1.0.2.tgz";
        sha1 = "a21904a12c04f65cba9ea7fbfb9ac2e05f09208e";
      };
    };
    "https-proxy-agent-5.0.0" = {
      name = "https-proxy-agent";
      packageName = "https-proxy-agent";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/https-proxy-agent/-/https-proxy-agent-5.0.0.tgz";
        sha512 = "EkYm5BcKUGiduxzSt3Eppko+PiNWNEpa4ySk9vTC6wDsQJW9rHSa+UhGNJoRYp7bz6Ht1eaRIa6QaJqO5rCFbA==";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "ip-1.1.5" = {
      name = "ip";
      packageName = "ip";
      version = "1.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/ip/-/ip-1.1.5.tgz";
        sha1 = "bdded70114290828c0a039e72ef25f5aaec4354a";
      };
    };
    "is-absolute-1.0.0" = {
      name = "is-absolute";
      packageName = "is-absolute";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-absolute/-/is-absolute-1.0.0.tgz";
        sha512 = "dOWoqflvcydARa360Gvv18DZ/gRuHKi2NU/wU5X1ZFzdYfH29nkiNZsF3mp4OJ3H4yo9Mx8A/uAGNzpzPN3yBA==";
      };
    };
    "is-arguments-1.0.4" = {
      name = "is-arguments";
      packageName = "is-arguments";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-arguments/-/is-arguments-1.0.4.tgz";
        sha512 = "xPh0Rmt8NE65sNzvyUmWgI1tz3mKq74lGA0mL8LYZcoIzKOzDh6HmrYm3d18k60nHerC8A9Km8kYu87zfSFnLA==";
      };
    };
    "is-callable-1.1.5" = {
      name = "is-callable";
      packageName = "is-callable";
      version = "1.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-callable/-/is-callable-1.1.5.tgz";
        sha512 = "ESKv5sMCJB2jnHTWZ3O5itG+O128Hsus4K4Qh1h2/cgn2vbgnLSVqfV46AeJA9D5EeeLa9w81KUXMtn34zhX+Q==";
      };
    };
    "is-date-object-1.0.2" = {
      name = "is-date-object";
      packageName = "is-date-object";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-date-object/-/is-date-object-1.0.2.tgz";
        sha512 = "USlDT524woQ08aoZFzh3/Z6ch9Y/EWXEHQ/AaRN0SkKq4t2Jw2R2339tSXmwuVoY7LLlBCbOIlx2myP/L5zk0g==";
      };
    };
    "is-extglob-2.1.1" = {
      name = "is-extglob";
      packageName = "is-extglob";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extglob/-/is-extglob-2.1.1.tgz";
        sha1 = "a88c02535791f02ed37c76a1b9ea9773c833f8c2";
      };
    };
    "is-glob-3.1.0" = {
      name = "is-glob";
      packageName = "is-glob";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-glob/-/is-glob-3.1.0.tgz";
        sha1 = "7ba5ae24217804ac70707b96922567486cc3e84a";
      };
    };
    "is-negated-glob-1.0.0" = {
      name = "is-negated-glob";
      packageName = "is-negated-glob";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-negated-glob/-/is-negated-glob-1.0.0.tgz";
        sha1 = "6910bca5da8c95e784b5751b976cf5a10fee36d2";
      };
    };
    "is-regex-1.0.5" = {
      name = "is-regex";
      packageName = "is-regex";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-regex/-/is-regex-1.0.5.tgz";
        sha512 = "vlKW17SNq44owv5AQR3Cq0bQPEb8+kF3UKZ2fiZNOWtztYE5i0CzCZxFDwO58qAOWtxdBRVO/V5Qin1wjCqFYQ==";
      };
    };
    "is-relative-1.0.0" = {
      name = "is-relative";
      packageName = "is-relative";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-relative/-/is-relative-1.0.0.tgz";
        sha512 = "Kw/ReK0iqwKeu0MITLFuj0jbPAmEiOsIwyIXvvbfa6QfmN9pkD1M+8pdk7Rl/dTKbH34/XBFMbgD4iMJhLQbGA==";
      };
    };
    "is-stream-2.0.0" = {
      name = "is-stream";
      packageName = "is-stream";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-stream/-/is-stream-2.0.0.tgz";
        sha512 = "XCoy+WlUr7d1+Z8GgSuXmpuUFC9fOhRXglJMx+dwLKTkL44Cjd4W1Z5P+BQZpr+cR93aGP4S/s7Ftw6Nd/kiEw==";
      };
    };
    "is-symbol-1.0.3" = {
      name = "is-symbol";
      packageName = "is-symbol";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-symbol/-/is-symbol-1.0.3.tgz";
        sha512 = "OwijhaRSgqvhm/0ZdAcXNZt9lYdKFpcRDT5ULUuYXPoT794UNOdU+gpT6Rzo7b4V2HUl/op6GqY894AZwv9faQ==";
      };
    };
    "is-unc-path-1.0.0" = {
      name = "is-unc-path";
      packageName = "is-unc-path";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-unc-path/-/is-unc-path-1.0.0.tgz";
        sha512 = "mrGpVd0fs7WWLfVsStvgF6iEJnbjDFZh9/emhRDcGWTduTfNHd9CHeUwH3gYIjdbwo4On6hunkztwOaAw0yllQ==";
      };
    };
    "is-windows-1.0.2" = {
      name = "is-windows";
      packageName = "is-windows";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-windows/-/is-windows-1.0.2.tgz";
        sha512 = "eXK1UInq2bPmjyX6e3VHIzMLobc4J94i4AWn+Hpq3OU5KkrRC96OAcR3PRJ/pGu6m8TRnBHP9dkXQVsT/COVIA==";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "json-bigint-0.3.0" = {
      name = "json-bigint";
      packageName = "json-bigint";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-bigint/-/json-bigint-0.3.0.tgz";
        sha1 = "0ccd912c4b8270d05f056fbd13814b53d3825b1e";
      };
    };
    "json-stable-stringify-without-jsonify-1.0.1" = {
      name = "json-stable-stringify-without-jsonify";
      packageName = "json-stable-stringify-without-jsonify";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stable-stringify-without-jsonify/-/json-stable-stringify-without-jsonify-1.0.1.tgz";
        sha1 = "9db7b59496ad3f3cfef30a75142d2d930ad72651";
      };
    };
    "jwa-2.0.0" = {
      name = "jwa";
      packageName = "jwa";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jwa/-/jwa-2.0.0.tgz";
        sha512 = "jrZ2Qx916EA+fq9cEAeCROWPTfCwi1IVHqT2tapuqLEVVDKFDENFw1oL+MwrTvH6msKxsd1YTDVw6uKEcsrLEA==";
      };
    };
    "jws-4.0.0" = {
      name = "jws";
      packageName = "jws";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jws/-/jws-4.0.0.tgz";
        sha512 = "KDncfTmOZoOMTFG4mBlG0qUIOlc03fmzH+ru6RgYVZhPkyiy/92Owlt/8UEN+a4TXR1FQetfIpJE8ApdvdVxTg==";
      };
    };
    "leven-2.1.0" = {
      name = "leven";
      packageName = "leven";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/leven/-/leven-2.1.0.tgz";
        sha1 = "c2e7a9f772094dee9d34202ae8acce4687875580";
      };
    };
    "lru-cache-5.1.1" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-5.1.1.tgz";
        sha512 = "KpNARQA3Iwv+jTA0utUVVbrh+Jlrr1Fv0e56GGzAFOXN7dk/FviaDW8LHmK52DlcH4WP2n6gI8vN1aesBFgo9w==";
      };
    };
    "mime-2.4.4" = {
      name = "mime";
      packageName = "mime";
      version = "2.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-2.4.4.tgz";
        sha512 = "LRxmNwziLPT828z+4YkNzloCFC2YM4wrB99k+AV5ZbEyfGNWfG8SO1FUXLmLDBSo89NrJZ4DIWeLjy1CHGhMGA==";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==";
      };
    };
    "minimist-1.2.5" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.5.tgz";
        sha512 = "FM9nNUYrRBAELZQT3xeZQ7fmMOBg6nWNmJKTcgsJeaLstP/UODVpGsr5OhXhhXg6f+qtJ8uiZ+PUxkDWcgIXLw==";
      };
    };
    "mkdirp-0.3.5" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.3.5.tgz";
        sha1 = "de3e5f8961c88c787ee1368df849ac4413eca8d7";
      };
    };
    "mkdirp-0.5.5" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.5.tgz";
        sha512 = "NKmAlESf6jMGym1++R0Ra7wvhV+wFW63FaSOFPwRahvea0gMUcGUhVeAg/0BC0wiv9ih5NYPB1Wn1UEI1/L+xQ==";
      };
    };
    "moment-2.24.0" = {
      name = "moment";
      packageName = "moment";
      version = "2.24.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/moment/-/moment-2.24.0.tgz";
        sha512 = "bV7f+6l2QigeBBZSM/6yTNq4P2fNpSWj/0e7jQcy87A8e7o2nAfP/34/2ky5Vw4B9S446EtIhodAzkFCcR4dQg==";
      };
    };
    "mqtt-2.18.8" = {
      name = "mqtt";
      packageName = "mqtt";
      version = "2.18.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/mqtt/-/mqtt-2.18.8.tgz";
        sha512 = "3h6oHlPY/yWwtC2J3geraYRtVVoRM6wdI+uchF4nvSSafXPZnaKqF8xnX+S22SU/FcgEAgockVIlOaAX3fkMpA==";
      };
    };
    "mqtt-packet-5.6.1" = {
      name = "mqtt-packet";
      packageName = "mqtt-packet";
      version = "5.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mqtt-packet/-/mqtt-packet-5.6.1.tgz";
        sha512 = "eaF9rO2uFrIYEHomJxziuKTDkbWW5psLBaIGCazQSKqYsTaB3n4SpvJ1PexKaDBiPnMLPIFWBIiTYT3IfEJfww==";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha1 = "5608aeadfc00be6c2901df5f9861788de0d597c8";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "multicast-dns-7.2.2" = {
      name = "multicast-dns";
      packageName = "multicast-dns";
      version = "7.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/multicast-dns/-/multicast-dns-7.2.2.tgz";
        sha512 = "XqSMeO8EWV/nOXOpPV8ztIpNweVfE1dSpz6SQvDPp71HD74lMXjt4m/mWB1YBMG0kHtOodxRWc5WOb/UNN1A5g==";
      };
    };
    "multicast-dns-service-types-1.1.0" = {
      name = "multicast-dns-service-types";
      packageName = "multicast-dns-service-types";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/multicast-dns-service-types/-/multicast-dns-service-types-1.1.0.tgz";
        sha1 = "899f11d9686e5e05cb91b35d5f0e63b773cfc901";
      };
    };
    "next-tick-1.0.0" = {
      name = "next-tick";
      packageName = "next-tick";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/next-tick/-/next-tick-1.0.0.tgz";
        sha1 = "ca86d1fe8828169b0120208e3dc8424b9db8342c";
      };
    };
    "node-fetch-2.6.0" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "2.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-2.6.0.tgz";
        sha512 = "8dG4H5ujfvFiqDmVu9fQ5bOHUC15JMjMY/Zumv26oOvvVJjM67KF8koCWIabKQ1GJIa9r2mMZscBq/TbdOcmNA==";
      };
    };
    "node-forge-0.9.1" = {
      name = "node-forge";
      packageName = "node-forge";
      version = "0.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-forge/-/node-forge-0.9.1.tgz";
        sha512 = "G6RlQt5Sb4GMBzXvhfkeFmbqR6MzhtnT7VTHuLadjkii3rdYHNdw0m8zA4BTxVIh68FicCQ2NSUANpsqkr9jvQ==";
      };
    };
    "node-persist-0.0.11" = {
      name = "node-persist";
      packageName = "node-persist";
      version = "0.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-persist/-/node-persist-0.0.11.tgz";
        sha1 = "d66eba3ebef620f079530fa7b13076a906665874";
      };
    };
    "node-persist-0.0.8" = {
      name = "node-persist";
      packageName = "node-persist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-persist/-/node-persist-0.0.8.tgz";
        sha1 = "a56c739bc6ffd9ceef19c0e8d89597917f089249";
      };
    };
    "object-inspect-1.7.0" = {
      name = "object-inspect";
      packageName = "object-inspect";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-inspect/-/object-inspect-1.7.0.tgz";
        sha512 = "a7pEHdh1xKIAgTySUGgLMx/xwDZskN1Ud6egYYN3EdRW4ZMPNEDUTF+hwy2LUC+Bl+SyLXANnwz/jyh/qutKUw==";
      };
    };
    "object-is-1.1.2" = {
      name = "object-is";
      packageName = "object-is";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-is/-/object-is-1.1.2.tgz";
        sha512 = "5lHCz+0uufF6wZ7CRFWJN3hp8Jqblpgve06U5CMQ3f//6iDjPr2PEo9MWCjEssDsa+UZEL4PkFpr+BMop6aKzQ==";
      };
    };
    "object-keys-1.1.1" = {
      name = "object-keys";
      packageName = "object-keys";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-keys/-/object-keys-1.1.1.tgz";
        sha512 = "NuAESUOUMrlIXOfHKzD6bpPu3tYt3xvjNdRIQ+FeT0lNb4K8WR70CaDxhuNguS2XG+GjkyMwOzsN5ZktImfhLA==";
      };
    };
    "object.assign-4.1.0" = {
      name = "object.assign";
      packageName = "object.assign";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.assign/-/object.assign-4.1.0.tgz";
        sha512 = "exHJeq6kBKj58mqGyTQ9DFvrZC/eR6OwxzoM9YRoGBqrXYonaFyGiFMuc9VZrXf7DarreEwMpurG3dd+CNyW5w==";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "ordered-read-streams-1.0.1" = {
      name = "ordered-read-streams";
      packageName = "ordered-read-streams";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ordered-read-streams/-/ordered-read-streams-1.0.1.tgz";
        sha1 = "77c0cb37c41525d64166d990ffad7ec6a0e1363e";
      };
    };
    "path-dirname-1.0.2" = {
      name = "path-dirname";
      packageName = "path-dirname";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-dirname/-/path-dirname-1.0.2.tgz";
        sha1 = "cc33d24d525e099a5388c0336c6e32b9160609e0";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "process-nextick-args-2.0.1" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-2.0.1.tgz";
        sha512 = "3ouUOpQhtgrbOa17J7+uxOTpITYWaGP7/AhoR3+A+/1e9skrzelGi/dXzEYyvbxubEF6Wn2ypscTKiKJFFn1ag==";
      };
    };
    "pump-2.0.1" = {
      name = "pump";
      packageName = "pump";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pump/-/pump-2.0.1.tgz";
        sha512 = "ruPMNRkN3MHP1cWJc9OWr+T/xDP0jhXYCLfJcBuX54hhfIBnaQmAUMfDcG4DM5UMWByBbJY69QSphm3jtDKIkA==";
      };
    };
    "pump-3.0.0" = {
      name = "pump";
      packageName = "pump";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pump/-/pump-3.0.0.tgz";
        sha512 = "LwZy+p3SFs1Pytd/jYct4wpv49HiYCqd9Rlc5ZVdk0V+8Yzv6jR5Blk3TRmPL1ft69TxP0IMZGJ+WPFU2BFhww==";
      };
    };
    "pumpify-1.5.1" = {
      name = "pumpify";
      packageName = "pumpify";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pumpify/-/pumpify-1.5.1.tgz";
        sha512 = "oClZI37HvuUJJxSKKrC17bZ9Cu0ZYhEAGPsPUy9KlMUmv9dKX2o77RUmq7f3XjIxbwyGwYzbzQ1L2Ks8sIradQ==";
      };
    };
    "put-0.0.6" = {
      name = "put";
      packageName = "put";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/put/-/put-0.0.6.tgz";
        sha1 = "30f5f60bd6e4389bd329e16a25386cbb2e4a00a3";
      };
    };
    "q-1.1.2" = {
      name = "q";
      packageName = "q";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/q/-/q-1.1.2.tgz";
        sha1 = "6357e291206701d99f197ab84e57e8ad196f2a89";
      };
    };
    "qrcode-terminal-0.11.0" = {
      name = "qrcode-terminal";
      packageName = "qrcode-terminal";
      version = "0.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/qrcode-terminal/-/qrcode-terminal-0.11.0.tgz";
        sha1 = "ffc6c28a2fc0bfb47052b47e23f4f446a5fbdb9e";
      };
    };
    "qs-6.9.3" = {
      name = "qs";
      packageName = "qs";
      version = "6.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.9.3.tgz";
        sha512 = "EbZYNarm6138UKKq46tdx08Yo/q9ZhFoAXAI1meAFd2GtbRDhbZY2WQSICskT0c5q99aFzLG1D4nvTk9tqfXIw==";
      };
    };
    "readable-stream-2.3.7" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.3.7.tgz";
        sha512 = "Ebho8K4jIbHAxnuxi7o42OrZgF/ZTNcsZj6nRKyUmkhLFq8CHItp/fy6hQZuZmP/n3yZ9VBUbp4zz/mX8hmYPw==";
      };
    };
    "regexp.prototype.flags-1.3.0" = {
      name = "regexp.prototype.flags";
      packageName = "regexp.prototype.flags";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/regexp.prototype.flags/-/regexp.prototype.flags-1.3.0.tgz";
        sha512 = "2+Q0C5g951OlYlJz6yu5/M33IcsESLlLfsyIaLJaG4FA2r4yP8MvVMJUUP/fVBkSpbbbZlS5gynbEWLipiiXiQ==";
      };
    };
    "reinterval-1.1.0" = {
      name = "reinterval";
      packageName = "reinterval";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/reinterval/-/reinterval-1.1.0.tgz";
        sha1 = "3361ecfa3ca6c18283380dd0bb9546f390f5ece7";
      };
    };
    "remove-trailing-separator-1.1.0" = {
      name = "remove-trailing-separator";
      packageName = "remove-trailing-separator";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remove-trailing-separator/-/remove-trailing-separator-1.1.0.tgz";
        sha1 = "c24bce2a283adad5bc3f58e0d48249b92379d8ef";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "safe-buffer-5.2.0" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.0.tgz";
        sha512 = "fZEwUGbVl7kouZs1jCdMLdt95hdIv0ZeHg6L7qPeciMZhZ+/gdesW4wgTARkrFWEpspjEATAzUGPG8N2jJiwbg==";
      };
    };
    "sax-0.4.3" = {
      name = "sax";
      packageName = "sax";
      version = "0.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sax/-/sax-0.4.3.tgz";
        sha1 = "700e3a34eb2e792ce380791c71280f3731965ddc";
      };
    };
    "semver-5.0.3" = {
      name = "semver";
      packageName = "semver";
      version = "5.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.0.3.tgz";
        sha1 = "77466de589cd5d3c95f138aa78bc569a3cb5d27a";
      };
    };
    "semver-7.1.2" = {
      name = "semver";
      packageName = "semver";
      version = "7.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.1.2.tgz";
        sha512 = "BJs9T/H8sEVHbeigqzIEo57Iu/3DG6c4QoqTfbQB3BPA4zgzAomh/Fk9E7QtjWQ8mx2dgA9YCfSF4y9k9bHNpQ==";
      };
    };
    "semver-7.2.3" = {
      name = "semver";
      packageName = "semver";
      version = "7.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.2.3.tgz";
        sha512 = "utbW9Z7ZxVvwiIWkdOMLOR9G/NFXh2aRucghkVrEMJWuC++r3lCkBC3LwqBinyHzGMAJxY5tn6VakZGHObq5ig==";
      };
    };
    "split2-2.2.0" = {
      name = "split2";
      packageName = "split2";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/split2/-/split2-2.2.0.tgz";
        sha512 = "RAb22TG39LhI31MbreBgIuKiIKhVsawfTgEGqKHTK87aG+ul/PB8Sqoi3I7kVdRWiCfrKxK3uo4/YUkpNvhPbw==";
      };
    };
    "sprintf-js-1.1.2" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.1.2.tgz";
        sha512 = "VE0SOVEHCk7Qc8ulkWw3ntAzXuqf7S2lvwQaDLRnUeIEaKNQJzV6BwmLKhOqT61aGhfUMrXeaBk+oDGCzvhcug==";
      };
    };
    "stream-shift-1.0.1" = {
      name = "stream-shift";
      packageName = "stream-shift";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-shift/-/stream-shift-1.0.1.tgz";
        sha512 = "AiisoFqQ0vbGcZgQPY1cdP2I76glaVA/RauYR4G4thNFgkTqr90yXTo4LYX60Jl+sIlPNHHdGSwo01AvbKUSVQ==";
      };
    };
    "string.prototype.trimend-1.0.1" = {
      name = "string.prototype.trimend";
      packageName = "string.prototype.trimend";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.trimend/-/string.prototype.trimend-1.0.1.tgz";
        sha512 = "LRPxFUaTtpqYsTeNKaFOw3R4bxIzWOnbQ837QfBylo8jIxtcbK/A/sMV7Q+OAV/vWo+7s25pOE10KYSjaSO06g==";
      };
    };
    "string.prototype.trimleft-2.1.2" = {
      name = "string.prototype.trimleft";
      packageName = "string.prototype.trimleft";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.trimleft/-/string.prototype.trimleft-2.1.2.tgz";
        sha512 = "gCA0tza1JBvqr3bfAIFJGqfdRTyPae82+KTnm3coDXkZN9wnuW3HjGgN386D7hfv5CHQYCI022/rJPVlqXyHSw==";
      };
    };
    "string.prototype.trimright-2.1.2" = {
      name = "string.prototype.trimright";
      packageName = "string.prototype.trimright";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.trimright/-/string.prototype.trimright-2.1.2.tgz";
        sha512 = "ZNRQ7sY3KroTaYjRS6EbNiiHrOkjihL9aQE/8gfQ4DtAC/aEBRHFJa44OmoWxGGqXuJlfKkZW4WcXErGr+9ZFg==";
      };
    };
    "string.prototype.trimstart-1.0.1" = {
      name = "string.prototype.trimstart";
      packageName = "string.prototype.trimstart";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.trimstart/-/string.prototype.trimstart-1.0.1.tgz";
        sha512 = "XxZn+QpvrBI1FOcg6dIpxUPgWCPuNXvMD72aaRaUQv1eD4e/Qy8i/hFTe0BUmD60p/QA6bh1avmuPTfNjqVWRw==";
      };
    };
    "string_decoder-1.1.1" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.1.1.tgz";
        sha512 = "n/ShnvDi6FHbbVfviro+WojiFzv+s8MPMHBczVePfUpDJLwoLT0ht1l4YwBCbi8pJAveEEdnkHyPyTP/mzRfwg==";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "supports-color-2.0.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz";
        sha1 = "535d045ce6b6363fa40117084629995e9df324c7";
      };
    };
    "supports-color-7.1.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "7.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-7.1.0.tgz";
        sha512 = "oRSIpR8pxT1Wr2FquTNnGet79b3BWljqOuoW/h4oBhxJ/HUbX5nX6JSruTkvXDCFMwDPvsaTTbvMLKZWSy0R5g==";
      };
    };
    "through2-2.0.5" = {
      name = "through2";
      packageName = "through2";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/through2/-/through2-2.0.5.tgz";
        sha512 = "/mrRod8xqpA+IHSLyGCQ2s8SPHiCDEeQJSep1jqLYeEUClOFG2Qsh+4FU6G9VeqpZnGW/Su8LQGc4YKni5rYSQ==";
      };
    };
    "through2-filter-3.0.0" = {
      name = "through2-filter";
      packageName = "through2-filter";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/through2-filter/-/through2-filter-3.0.0.tgz";
        sha512 = "jaRjI2WxN3W1V8/FMZ9HKIBXixtiqs3SQSX4/YGIiP3gL6djW48VoZq9tDqeCWs3MT8YY5wb/zli8VW8snY1CA==";
      };
    };
    "thunky-1.1.0" = {
      name = "thunky";
      packageName = "thunky";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/thunky/-/thunky-1.1.0.tgz";
        sha512 = "eHY7nBftgThBqOyHGVN+l8gF0BucP09fMo0oO/Lb0w1OF80dJv+lDVpXG60WMQvkcxAkNybKsrEIE3ZtKGmPrA==";
      };
    };
    "to-absolute-glob-2.0.2" = {
      name = "to-absolute-glob";
      packageName = "to-absolute-glob";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-absolute-glob/-/to-absolute-glob-2.0.2.tgz";
        sha1 = "1865f43d9e74b0822db9f145b78cff7d0f7c849b";
      };
    };
    "traverse-0.3.9" = {
      name = "traverse";
      packageName = "traverse";
      version = "0.3.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/traverse/-/traverse-0.3.9.tgz";
        sha1 = "717b8f220cc0bb7b44e40514c22b2e8bbc70d8b9";
      };
    };
    "tweetnacl-1.0.3" = {
      name = "tweetnacl";
      packageName = "tweetnacl";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tweetnacl/-/tweetnacl-1.0.3.tgz";
        sha512 = "6rt+RN7aOi1nGMyC4Xa5DdYiukl2UWCbcJft7YhxReBGQD7OAM8Pbxw6YMo4r2diNEA8FEmu32YOn9rhaiE5yw==";
      };
    };
    "type-1.2.0" = {
      name = "type";
      packageName = "type";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/type/-/type-1.2.0.tgz";
        sha512 = "+5nt5AAniqsCnu2cEQQdpzCAh33kVx8n0VoFidKpB1dVVLAN/F+bgVOqOJqOnEnrhp222clB5p3vUlD+1QAnfg==";
      };
    };
    "type-2.0.0" = {
      name = "type";
      packageName = "type";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/type/-/type-2.0.0.tgz";
        sha512 = "KBt58xCHry4Cejnc2ISQAF7QY+ORngsWfxezO68+12hKV6lQY8P/psIkcbjeHWn7MqcgciWJyCCevFMJdIXpow==";
      };
    };
    "typedarray-0.0.6" = {
      name = "typedarray";
      packageName = "typedarray";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/typedarray/-/typedarray-0.0.6.tgz";
        sha1 = "867ac74e3864187b1d3d47d996a78ec5c8830777";
      };
    };
    "ultron-1.1.1" = {
      name = "ultron";
      packageName = "ultron";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ultron/-/ultron-1.1.1.tgz";
        sha512 = "UIEXBNeYmKptWH6z8ZnqTeS8fV74zG0/eRU9VGkpzz+LIJNs8W/zM/L+7ctCkRrgbNnnR0xxw4bKOr0cW0N0Og==";
      };
    };
    "unc-path-regex-0.1.2" = {
      name = "unc-path-regex";
      packageName = "unc-path-regex";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/unc-path-regex/-/unc-path-regex-0.1.2.tgz";
        sha1 = "e73dd3d7b0d7c5ed86fbac6b0ae7d8c6a69d50fa";
      };
    };
    "unique-stream-2.3.1" = {
      name = "unique-stream";
      packageName = "unique-stream";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/unique-stream/-/unique-stream-2.3.1.tgz";
        sha512 = "2nY4TnBE70yoxHkDli7DMazpWiP7xMdCYqU2nBRO0UB+ZpEkGsSija7MvmvnZFUeC+mrgiUfcHSr3LmRFIg4+A==";
      };
    };
    "url-template-2.0.8" = {
      name = "url-template";
      packageName = "url-template";
      version = "2.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/url-template/-/url-template-2.0.8.tgz";
        sha1 = "fc565a3cccbff7730c775f5641f9555791439f21";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "uuid-7.0.3" = {
      name = "uuid";
      packageName = "uuid";
      version = "7.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-7.0.3.tgz";
        sha512 = "DPSke0pXhTZgoF/d+WSt2QaKMCFSfx7QegxEWT+JOuHF5aWrKEn0G+ztjuJg/gG8/ItK+rbPCD/yNv8yyih6Cg==";
      };
    };
    "websocket-stream-5.5.2" = {
      name = "websocket-stream";
      packageName = "websocket-stream";
      version = "5.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/websocket-stream/-/websocket-stream-5.5.2.tgz";
        sha512 = "8z49MKIHbGk3C4HtuHWDtYX8mYej1wWabjthC/RupM9ngeukU4IWoM46dgth1UOS/T4/IqgEdCDJuMe2039OQQ==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "ws-3.3.3" = {
      name = "ws";
      packageName = "ws";
      version = "3.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-3.3.3.tgz";
        sha512 = "nnWLa/NwZSt4KQJu51MYlCcSQ5g7INpOrOMt4XV8j4dqTXdmlUmSHQ8/oLC069ckre0fRsgfvsKwbTdtKLCDkA==";
      };
    };
    "xmlbuilder-https://github.com/hobbyquaker/xmlbuilder-js/tarball/29fe5030dc6852007dc8d1bfd5109d75f8da58d5" = {
      name = "xmlbuilder";
      packageName = "xmlbuilder";
      version = "0.4.2";
      src = fetchurl {
        name = "xmlbuilder-0.4.2.tar.gz";
        url = https://codeload.github.com/hobbyquaker/xmlbuilder-js/legacy.tar.gz/29fe5030dc6852007dc8d1bfd5109d75f8da58d5;
        sha256 = "e9cc588bfeb1130c09a8c8453b39da2d54b3e5861b1c7ebb42c3ec7e74c36972";
      };
    };
    "xtend-4.0.2" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.2.tgz";
        sha512 = "LKYU1iAXJXUgAXn9URjiu+MWhyUXHsvfp7mcuYm9dSUKK0/CjtrUwFAxD82/mCWbtLsGjFIad0wIsod4zrTAEQ==";
      };
    };
    "yallist-3.1.1" = {
      name = "yallist";
      packageName = "yallist";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-3.1.1.tgz";
        sha512 = "a4UGQaWPH59mOXUYnAG2ewncQS4i4F43Tv3JoAM+s2VDAmS9NsK8GpDMLrCHPksFT7h3K6TOoUNn2pb7RoXx4g==";
      };
    };
  };
in
{
  "homebridge-homematic-git+https://github.com/thkl/homebridge-homematic.git#0.1.220" = nodeEnv.buildNodePackage {
    name = "homebridge-homematic";
    packageName = "homebridge-homematic";
    version = "0.1.229";
    src = fetchgit {
      url = "https://github.com/thkl/homebridge-homematic.git";
      rev = "e1f872df79965a4782601375bae585c4f00b6c03";
      sha256 = "161bef5064a790445a9fa7947e7cdb913f2c065da462464844bdc711186db427";
    };
    dependencies = [
      sources."@types/color-name-1.1.1"
      sources."abort-controller-3.0.0"
      sources."agent-base-6.0.0"
      sources."ansi-styles-4.2.1"
      sources."arrify-2.0.1"
      sources."base64-js-1.3.1"
      sources."bignumber.js-7.2.1"
      sources."binary-0.3.0"
      sources."binrpc-3.3.1"
      sources."buffer-equal-constant-time-1.0.1"
      sources."buffers-0.1.1"
      sources."chainsaw-0.1.0"
      sources."chalk-4.0.0"
      sources."color-convert-2.0.1"
      sources."color-name-1.1.4"
      sources."debug-4.1.1"
      sources."ecdsa-sig-formatter-1.0.11"
      sources."event-target-shim-5.0.1"
      sources."extend-3.0.2"
      (sources."fakegato-history-0.5.6" // {
        dependencies = [
          sources."debug-2.6.9"
          sources."ms-2.0.0"
        ];
      })
      sources."fast-text-encoding-1.0.1"
      sources."gaxios-2.3.4"
      sources."gcp-metadata-3.5.0"
      sources."google-auth-library-5.9.2"
      sources."google-p12-pem-2.0.4"
      sources."googleapis-47.0.0"
      sources."googleapis-common-3.2.2"
      sources."gtoken-4.1.4"
      sources."has-flag-4.0.0"
      sources."homematic-xmlrpc-1.0.2"
      sources."https-proxy-agent-5.0.0"
      sources."ip-1.1.5"
      sources."is-stream-2.0.0"
      sources."json-bigint-0.3.0"
      sources."jwa-2.0.0"
      sources."jws-4.0.0"
      sources."lru-cache-5.1.1"
      sources."mime-2.4.4"
      sources."moment-2.24.0"
      sources."ms-2.1.2"
      sources."node-fetch-2.6.0"
      sources."node-forge-0.9.1"
      sources."put-0.0.6"
      sources."qs-6.9.3"
      sources."safe-buffer-5.2.0"
      sources."sax-0.4.3"
      sources."semver-7.1.2"
      sources."sprintf-js-1.1.2"
      sources."supports-color-7.1.0"
      sources."traverse-0.3.9"
      sources."url-template-2.0.8"
      sources."uuid-7.0.3"
      sources."xmlbuilder-https://github.com/hobbyquaker/xmlbuilder-js/tarball/29fe5030dc6852007dc8d1bfd5109d75f8da58d5"
      sources."yallist-3.1.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Homematic plugin for homebridge: https://github.com/nfarina/homebridge";
      license = "ISC";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "homebridge-mqttthing-git+https://github.com/arachnetech/homebridge-mqttthing.git#ver_1.1.8" = nodeEnv.buildNodePackage {
    name = "homebridge-mqttthing";
    packageName = "homebridge-mqttthing";
    version = "1.1.8";
    src = fetchgit {
      url = "https://github.com/arachnetech/homebridge-mqttthing.git";
      rev = "e0232edbb324a08dfd4da603f03451b828ec511d";
      sha256 = "bca4dc1c34771223abdaefc2675aa88a079ebfa2069e45952075cfdc5246c667";
    };
    dependencies = [
      sources."@types/color-name-1.1.1"
      sources."abort-controller-3.0.0"
      (sources."agent-base-6.0.0" // {
        dependencies = [
          sources."debug-4.1.1"
        ];
      })
      sources."ansi-styles-4.2.1"
      sources."array-flatten-2.1.2"
      sources."arrify-2.0.1"
      sources."async-limiter-1.0.1"
      sources."balanced-match-1.0.0"
      sources."base64-js-1.3.1"
      sources."bignumber.js-7.2.1"
      sources."bl-1.2.2"
      sources."bonjour-hap-3.5.4"
      sources."brace-expansion-1.1.11"
      sources."buffer-equal-constant-time-1.0.1"
      sources."buffer-from-1.1.1"
      sources."buffer-indexof-1.1.1"
      sources."callback-stream-1.1.0"
      sources."chalk-4.0.0"
      sources."color-convert-2.0.1"
      sources."color-name-1.1.4"
      sources."commist-1.1.0"
      sources."concat-map-0.0.1"
      sources."concat-stream-1.6.2"
      sources."core-util-is-1.0.2"
      sources."d-1.0.1"
      (sources."debug-2.6.9" // {
        dependencies = [
          sources."ms-2.0.0"
        ];
      })
      sources."deep-equal-1.1.1"
      sources."define-properties-1.1.3"
      sources."dns-equal-1.0.0"
      sources."dns-packet-4.2.0"
      sources."dns-txt-2.0.2"
      sources."duplexify-3.7.1"
      sources."ecdsa-sig-formatter-1.0.11"
      sources."end-of-stream-1.4.4"
      sources."es-abstract-1.17.5"
      sources."es-to-primitive-1.2.1"
      sources."es5-ext-0.10.53"
      sources."es6-iterator-2.0.3"
      sources."es6-map-0.1.5"
      (sources."es6-set-0.1.5" // {
        dependencies = [
          sources."es6-symbol-3.1.1"
        ];
      })
      sources."es6-symbol-3.1.3"
      sources."event-emitter-0.3.5"
      sources."event-target-shim-5.0.1"
      (sources."ext-1.4.0" // {
        dependencies = [
          sources."type-2.0.0"
        ];
      })
      sources."extend-3.0.2"
      sources."fakegato-history-0.5.6"
      sources."fast-text-encoding-1.0.1"
      sources."fs.realpath-1.0.0"
      sources."function-bind-1.1.1"
      sources."gaxios-3.0.2"
      sources."gcp-metadata-4.0.1"
      sources."glob-7.1.6"
      sources."glob-parent-3.1.0"
      sources."glob-stream-6.1.0"
      sources."google-auth-library-6.0.0"
      sources."google-p12-pem-3.0.1"
      sources."googleapis-49.0.0"
      sources."googleapis-common-4.1.0"
      sources."gtoken-5.0.1"
      sources."has-1.0.3"
      sources."has-flag-4.0.0"
      sources."has-symbols-1.0.1"
      sources."help-me-1.1.0"
      (sources."homebridge-lib-4.5.7" // {
        dependencies = [
          sources."debug-4.1.1"
        ];
      })
      (sources."https-proxy-agent-5.0.0" // {
        dependencies = [
          sources."debug-4.1.1"
        ];
      })
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."ip-1.1.5"
      sources."is-absolute-1.0.0"
      sources."is-arguments-1.0.4"
      sources."is-callable-1.1.5"
      sources."is-date-object-1.0.2"
      sources."is-extglob-2.1.1"
      sources."is-glob-3.1.0"
      sources."is-negated-glob-1.0.0"
      sources."is-regex-1.0.5"
      sources."is-relative-1.0.0"
      sources."is-stream-2.0.0"
      sources."is-symbol-1.0.3"
      sources."is-unc-path-1.0.0"
      sources."is-windows-1.0.2"
      sources."isarray-1.0.0"
      sources."json-bigint-0.3.0"
      sources."json-stable-stringify-without-jsonify-1.0.1"
      sources."jwa-2.0.0"
      sources."jws-4.0.0"
      sources."leven-2.1.0"
      sources."lru-cache-5.1.1"
      sources."mime-2.4.4"
      sources."minimatch-3.0.4"
      sources."minimist-1.2.5"
      sources."moment-2.24.0"
      sources."mqtt-2.18.8"
      sources."mqtt-packet-5.6.1"
      sources."ms-2.1.2"
      sources."multicast-dns-7.2.2"
      sources."multicast-dns-service-types-1.1.0"
      sources."next-tick-1.0.0"
      sources."node-fetch-2.6.0"
      sources."node-forge-0.9.1"
      sources."object-inspect-1.7.0"
      sources."object-is-1.1.2"
      sources."object-keys-1.1.1"
      sources."object.assign-4.1.0"
      sources."once-1.4.0"
      sources."ordered-read-streams-1.0.1"
      sources."path-dirname-1.0.2"
      sources."path-is-absolute-1.0.1"
      sources."process-nextick-args-2.0.1"
      sources."pump-3.0.0"
      (sources."pumpify-1.5.1" // {
        dependencies = [
          sources."pump-2.0.1"
        ];
      })
      sources."qs-6.9.3"
      (sources."readable-stream-2.3.7" // {
        dependencies = [
          sources."safe-buffer-5.1.2"
        ];
      })
      sources."regexp.prototype.flags-1.3.0"
      sources."reinterval-1.1.0"
      sources."remove-trailing-separator-1.1.0"
      sources."safe-buffer-5.2.0"
      sources."semver-7.2.3"
      sources."split2-2.2.0"
      sources."stream-shift-1.0.1"
      sources."string.prototype.trimend-1.0.1"
      sources."string.prototype.trimleft-2.1.2"
      sources."string.prototype.trimright-2.1.2"
      sources."string.prototype.trimstart-1.0.1"
      (sources."string_decoder-1.1.1" // {
        dependencies = [
          sources."safe-buffer-5.1.2"
        ];
      })
      sources."supports-color-7.1.0"
      sources."through2-2.0.5"
      sources."through2-filter-3.0.0"
      sources."thunky-1.1.0"
      sources."to-absolute-glob-2.0.2"
      sources."type-1.2.0"
      sources."typedarray-0.0.6"
      sources."ultron-1.1.1"
      sources."unc-path-regex-0.1.2"
      sources."unique-stream-2.3.1"
      sources."url-template-2.0.8"
      sources."util-deprecate-1.0.2"
      sources."uuid-7.0.3"
      sources."websocket-stream-5.5.2"
      sources."wrappy-1.0.2"
      (sources."ws-3.3.3" // {
        dependencies = [
          sources."safe-buffer-5.1.2"
        ];
      })
      sources."xtend-4.0.2"
      sources."yallist-3.1.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Homebridge plugin supporting various services over MQTT";
      homepage = "https://github.com/arachnetech/homebridge-mqttthing#readme";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "homebridge-git+https://github.com/nfarina/homebridge.git#0.4.53" = nodeEnv.buildNodePackage {
    name = "homebridge";
    packageName = "homebridge";
    version = "0.4.53";
    src = fetchgit {
      url = "https://github.com/nfarina/homebridge.git";
      rev = "9c022d031b40feed4111699b0ebdac1faf4deb55";
      sha256 = "332286c19498ff64815e1c05af61ea8f3ec1af94c644ca7d4129e7da76034eb5";
    };
    dependencies = [
      sources."ansi-regex-2.1.1"
      sources."ansi-styles-2.2.1"
      sources."array-flatten-2.1.2"
      sources."bonjour-hap-3.5.4"
      sources."buffer-indexof-1.1.1"
      sources."buffer-shims-1.0.0"
      sources."chalk-1.1.3"
      sources."commander-2.8.1"
      sources."debug-2.6.9"
      sources."decimal.js-7.5.1"
      sources."deep-equal-1.1.1"
      sources."define-properties-1.1.3"
      sources."dns-equal-1.0.0"
      sources."dns-packet-4.2.0"
      sources."dns-txt-2.0.2"
      sources."es-abstract-1.17.5"
      sources."es-to-primitive-1.2.1"
      sources."escape-string-regexp-1.0.5"
      sources."fast-srp-hap-1.2.0"
      sources."function-bind-1.1.1"
      sources."graceful-readlink-1.0.1"
      (sources."hap-nodejs-0.4.51" // {
        dependencies = [
          sources."node-persist-0.0.11"
        ];
      })
      sources."has-1.0.3"
      sources."has-ansi-2.0.0"
      sources."has-symbols-1.0.1"
      sources."ip-1.1.5"
      sources."is-arguments-1.0.4"
      sources."is-callable-1.1.5"
      sources."is-date-object-1.0.2"
      sources."is-regex-1.0.5"
      sources."is-symbol-1.0.3"
      sources."minimist-1.2.5"
      sources."mkdirp-0.5.5"
      sources."ms-2.0.0"
      sources."multicast-dns-7.2.2"
      sources."multicast-dns-service-types-1.1.0"
      (sources."node-persist-0.0.8" // {
        dependencies = [
          sources."mkdirp-0.3.5"
        ];
      })
      sources."object-inspect-1.7.0"
      sources."object-is-1.1.2"
      sources."object-keys-1.1.1"
      sources."object.assign-4.1.0"
      sources."q-1.1.2"
      sources."qrcode-terminal-0.11.0"
      sources."regexp.prototype.flags-1.3.0"
      sources."safe-buffer-5.2.0"
      sources."semver-5.0.3"
      sources."string.prototype.trimend-1.0.1"
      sources."string.prototype.trimleft-2.1.2"
      sources."string.prototype.trimright-2.1.2"
      sources."string.prototype.trimstart-1.0.1"
      sources."strip-ansi-3.0.1"
      sources."supports-color-2.0.0"
      sources."thunky-1.1.0"
      sources."tweetnacl-1.0.3"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "HomeKit support for the impatient";
      license = "ISC";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}